baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'Snaperture - things i capture'
copyright = 'Copyright © 2025, Tom Harris'
author = 'Tom Harris'
theme = 'hugo-bearblog'
enableRobotsTXT = true
